server:
  port: 8080
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    azure:
      storage:
        blob:
          container-name: lapenglish
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/lapenglish?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      connect-timeout: 3000


  cache:
    type: redis
    redis:
      cache-null-values: true
      time-to-live: 3600000
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
      file-size-threshold: 2MB

azure:
  blob-storage:
    connection-string: ${AZURE_STORAGE_CONNECTION_STRING}
    account-key:
    account-name:

springdoc:
  api-docs:
    enabled: true
    swagger-ui:
      enabled: true

#open:
#  api:
#    title: ${API_TITLE:DUMMY API}
#    description: Description of the API
#    version: 1.0.0
#    serverUrl: http://localhost:${server.port}
#    serverName: server test